name: doorapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Supabase for auth + realtime
  supabase_flutter: ^2.9.1

  # ✅ Networking
  http: ^1.2.2

  # ✅ Notifications + vibration
  flutter_local_notifications: ^17.2.1+2

  # ✅ Firebase core + messaging
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

  # ✅ Local DB for saving alerts
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ✅ Timezone utils for scheduling
  #flutter_timezone: ^2.1.0
  timezone: ^0.9.3
  flutter_timezone: ^4.1.1

  # ✅ Wi-Fi functionality
  wifi_scan: ^0.4.1+2
  wifi_iot: ^0.3.18
  permission_handler: ^12.0.0

  # ✅ State management
  provider: ^6.1.1

  # ✅ Icons + crypto
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3

  mailer: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assetss/logos.jpg
