// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCC5hUAI7KcLApsB0xxNid6kNnGKmcAQ',
    appId: '1:706423712400:web:23f8971d986fd0a3888615',
    messagingSenderId: '706423712400',
    projectId: 'noentry-1f3f6',
    authDomain: 'noentry-1f3f6.firebaseapp.com',
    storageBucket: 'noentry-1f3f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6uzLkYp8nyHtN23ZzHMhXBpeJBrffog',
    appId: '1:706423712400:android:72140056c29f184a888615',
    messagingSenderId: '706423712400',
    projectId: 'noentry-1f3f6',
    storageBucket: 'noentry-1f3f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA777yfeuDoHzk8LhH_xDzdrrQi6EGQAY8',
    appId: '1:706423712400:ios:967805ea289b0bde888615',
    messagingSenderId: '706423712400',
    projectId: 'noentry-1f3f6',
    storageBucket: 'noentry-1f3f6.firebasestorage.app',
    iosBundleId: 'com.example.doorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA777yfeuDoHzk8LhH_xDzdrrQi6EGQAY8',
    appId: '1:706423712400:ios:967805ea289b0bde888615',
    messagingSenderId: '706423712400',
    projectId: 'noentry-1f3f6',
    storageBucket: 'noentry-1f3f6.firebasestorage.app',
    iosBundleId: 'com.example.doorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCC5hUAI7KcLApsB0xxNid6kNnGKmcAQ',
    appId: '1:706423712400:web:c477591b1afb21ff888615',
    messagingSenderId: '706423712400',
    projectId: 'noentry-1f3f6',
    authDomain: 'noentry-1f3f6.firebaseapp.com',
    storageBucket: 'noentry-1f3f6.firebasestorage.app',
  );
}
