name: flutter_native_timezone
description: Fixed local plugin
version: 2.0.0
publish_to: 'none'

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.wolverinebeach.flutter_native_timezone
        pluginClass: FlutterNativeTimezonePlugin
